"""The doctrine generator: canonical YAML -> `docs/generated/DOCTRINE.md`.

    architecture/*.yaml  --generate-->  generated doctrine  --diff-->  gate
         (canonical)                      (projection)              pass/fail

WHY A GENERATOR AT ALL. Every phase in this repository so far ended in a
hand-written `docs/PHASE_*.md`, and each one restated architectural
facts that also live in code. That is how a synchronization window
silently drops an invariant: the prose and the enforcement diverge and
nobody can tell which is stale. Generated doctrine cannot drift, because
regeneration is a test.

WHAT DOCTRINE CONTAINS. Role behaviour and the constraints stated
abstractly. Not the binding table (`architecture/model_binding.yaml`),
not schemas, not enforcement code. `no_vendor_in_doctrine` is checked
against `forbidden_tokens` from `architecture/doctrine.yaml` PLUS every
vendor actually declared in `model_binding.yaml`, so instantiating a
binding automatically extends the lint rather than requiring someone to
remember to.

THE BUDGET FAILS CLOSED. `DoctrineBudgetExceeded` names the largest
section, because "doctrine is too long" is unactionable and "the
invariants section is 62% of the budget, move the enforcement detail to
invariants.yaml" is not.

DETERMINISM. Every iteration below is over a sorted or explicitly
ordered sequence, and no timestamp, path or environment value enters the
output. Generating twice produces identical bytes; that is asserted, not
assumed.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, List, Mapping, Tuple

from evidence.identity import content_hash

from epistemics._yaml import loads

REPO_ROOT = Path(__file__).resolve().parent.parent
ARCHITECTURE_DIR = REPO_ROOT / "architecture"
DOCTRINE_YAML = ARCHITECTURE_DIR / "doctrine.yaml"

_BANNER = "<!-- GENERATED by epistemics/doctrine.py from architecture/*.yaml. Do not edit. -->"


class DoctrineBudgetExceeded(ValueError):
    """Generated doctrine is over budget. Names the largest section."""


class VendorInDoctrine(ValueError):
    """A vendor identity reached the projection."""


@dataclass(frozen=True)
class Doctrine:
    text: str
    words: int
    budget: int
    source_digest: str
    sections: Tuple[Tuple[str, int], ...]


def _read(path: Path) -> Mapping[str, Any]:
    return loads(path.read_text())


def _words(text: str) -> int:
    return len(text.split())


def _section(title: str, lines: List[str]) -> str:
    return "\n".join([f"## {title}", ""] + lines + [""])


def _role_section(bindings_doc: Mapping[str, Any]) -> str:
    lines = ["| Role | Behaviour | Lineage |", "|---|---|---|"]
    for role, spec in sorted((bindings_doc.get("roles") or {}).items()):
        lines.append(f"| {role} | {spec['semantics']} | {spec['lineage']} |")
    lines += [
        "",
        "The accepting role must be vendor-independent from the proposing lineage.",
        "Which vendor serves which role is execution configuration and is not stated here.",
        "Different vendors are not thereby statistically independent; the requirement is a",
        "boundary requirement, not an independence claim.",
    ]
    return _section("Roles", lines)


def _loop_section(graph: Mapping[str, Any]) -> str:
    lines = ["The substrate is a loop entered at acquisition, not a stack entered at evidence.", ""]
    lines.append("```")
    for t in graph["transitions"]:
        lines.append(f"{t['from']} -> {t['to']}")
    lines.append("```")
    lines += ["", "The return edge is mandatory and exclusive. Forbidden edges:", ""]
    for f in graph["forbidden_transitions"]:
        lines.append(f"- `{f['from']} -> {f['to']}` -- {f['reason']}")
    return _section("Control loop", lines)


def _class_section(classes: Mapping[str, Any]) -> str:
    lines = [
        "Ingest classes: " + ", ".join(f"`{c}`" for c in classes["ingest_classes"]) + ".",
        "",
        "The class is fixed in the call that admits the object and there is no",
        "reclassification path. Absence of a class is `"
        + str(classes["migration_state"])
        + "`, which is inadmissible for canonical assertion and for training.",
        "",
        "Presentation and query terminology maps onto those classes:",
        "",
    ]
    for term, target in sorted(classes["vocabulary_map"].items()):
        lines.append(f"- `{term}` -> `{target}`")
    lines += [""]
    for status in classes["statuses_not_classes"]:
        lines.append(
            f"`{status}` is a claim-level status, never an evidence class. There is no"
            " promotion path from status to class."
        )
    return _section("Evidence classes", lines)


def _invariant_section(invariants_doc: Mapping[str, Any]) -> str:
    lines = ["| Invariant | Status |", "|---|---|"]
    for entry in invariants_doc["invariants"]:
        lines.append(f"| `{entry['id']}` | {entry['status']} |")
    lines += ["", "Rules and enforcement live in `architecture/invariants.yaml`."]
    return _section("Invariants", lines)


def _unresolved_section(invariants_doc: Mapping[str, Any]) -> str:
    lines = []
    for entry in invariants_doc.get("unresolved") or []:
        lines.append(f"- `{entry['id']}` -- {entry['detail']}")
    return _section("Unresolved", lines)


def generate(architecture_dir: Path = ARCHITECTURE_DIR) -> Doctrine:
    config = _read(architecture_dir / "doctrine.yaml")
    source_paths = [REPO_ROOT / rel for rel in config["sources"]]
    digest = content_hash({p.name: p.read_text() for p in sorted(source_paths)})

    core = _read(architecture_dir / "core.yaml")
    graph = _read(architecture_dir / "control_graph.yaml")
    classes = _read(architecture_dir / "evidence_class.yaml")
    invariants_doc = _read(architecture_dir / "invariants.yaml")
    bindings_doc = _read(architecture_dir / "model_binding.yaml")

    header = "\n".join(
        [
            _BANNER,
            f"<!-- source-digest: {digest} -->",
            "",
            "# Doctrine",
            "",
            f"Projection of `architecture/` at `core@{core['version']}`.",
            "This document is authoritative for nothing. Edit the canonical YAML instead.",
            "",
        ]
    )

    sections: List[Tuple[str, str]] = [
        ("Control loop", _loop_section(graph)),
        ("Evidence classes", _class_section(classes)),
        ("Roles", _role_section(bindings_doc)),
        ("Invariants", _invariant_section(invariants_doc)),
        ("Unresolved", _unresolved_section(invariants_doc)),
    ]

    text = header + "\n".join(body for _, body in sections)
    sizes = tuple((title, _words(body)) for title, body in sections)
    total = _words(text)
    budget = int(config["budget"]["max_words"])

    _lint_vendor(text, config, bindings_doc)

    if total > budget:
        largest = max(sizes, key=lambda s: s[1])
        raise DoctrineBudgetExceeded(
            f"generated doctrine is {total} words against a budget of {budget}. "
            f"The largest section is {largest[0]!r} at {largest[1]} words "
            f"({100 * largest[1] // max(total, 1)}% of the document). "
            "Move structural information to schemas, machine-enforced constraints to "
            "invariants, execution configuration to bindings, and domain structure to "
            "vertical contracts. Do not raise the budget."
        )

    return Doctrine(text=text, words=total, budget=budget, source_digest=digest, sections=sizes)


def _lint_vendor(text: str, config: Mapping[str, Any], bindings_doc: Mapping[str, Any]) -> None:
    forbidden = list(config.get("forbidden_tokens") or [])
    declared: Mapping[str, Mapping[str, Any]] = bindings_doc.get("bindings") or {}
    for spec in declared.values():
        forbidden.append(str(spec.get("vendor", "")))
        forbidden.append(str(spec.get("snapshot", "")))
    lowered = text.lower()
    hits = sorted({t for t in forbidden if t and t.lower() in lowered})
    if hits:
        raise VendorInDoctrine(
            f"generated doctrine names {hits}; vendor identity belongs in "
            "architecture/model_binding.yaml, adapters and runtime, never in doctrine"
        )


def output_path(architecture_dir: Path = ARCHITECTURE_DIR) -> Path:
    return REPO_ROOT / _read(architecture_dir / "doctrine.yaml")["output"]


def write(architecture_dir: Path = ARCHITECTURE_DIR) -> Path:
    doctrine = generate(architecture_dir)
    path = output_path(architecture_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(doctrine.text)
    return path
